using GymPal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GymPal.Interfaces
{
    // Interface for performing CRUD operations on a database.
    // This interface does not include UPDATE definitions since records generated by the application are intended to be immutable.
    public interface IRepository
    {
        /// <summary>
        /// Add a single record to the database.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="record"></param>
        /// <returns>The number of rows affected by the operation.</returns>
        Task<int> AddRecordAsync<T>(T record) where T : class;

        /// <summary>
        /// Add multiple records to the database in a single operation.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="records"></param>
        /// <returns>The number of rows affected by the operation.</returns>
        Task<int> AddRecords<T>(IEnumerable<T> records) where T : class;

        /// <summary>
        /// Retrieve a single record from the database.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="record"></param>
        /// <returns>The first entity returned by the operation.</returns>
        Task<T> GetRecordAsync<T>(T record) where T : class;

        /// <summary>
        /// Retrieve multiple records from the database in a single operation.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="records"></param>
        /// <returns>All records returned by the operation.</returns>
        Task<T> GetRecordsAsync<T>(IEnumerable<T> records) where T : class;

        /// <summary>
        /// Delete a single record from the database.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="record"></param>
        /// <returns>The number of rows affected by the operation.</returns>
        Task<int> DeleteRecordAsync<T>(T record) where T : class;
    }
}
